# secrets.yaml 은 .gitignore에 반드시 추가할 것.

korea_invest:
  virtual:
    app_key: "YOUR VIRTUAL APP KEY"
    app_secret: "YOUR VIRTUAL APP SECRET"
    account_no: "YOUR ACCOUNT"
    account_product_code: "account 뒷자리 숫자 2개"
    base_url: ""

  # 나중에 실계좌 쓰고 싶을 때
  real:
    app_key: "YOUR REAL APP KEY"
    app_secret: "YOUR REAL APP SECRET"
    account_no: "YOUR REAL ACCOUNT"
    account_product_code: "account 뒷자리 숫자 2개"
    base_url: ""

  

#텔레그램
telegram:
  enabled: true
  token: "YOUR TELEGRAM TOKEN"
  chat_id: "YOUR TELEGRAM CHAT ID"

